[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "py_nucflag"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = ["polars"]

[tool.maturin]
features = ["pyo3/extension-module"]

# Adapted from https://github.com/fiberseq/Molecular-annotation-spec/blob/main/python/pyproject.toml
[tool.pixi.workspace]
name = "py_nucflag"
channels = ["conda-forge", "bioconda"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pixi.dependencies]
python = ">=3.8,<3.13"
maturin = ">=1.8,<2.0"
tomlkit = "*"
pytest = ">=7"
pip = "*"
polars = "*"

[tool.pixi.pypi-dependencies]
py_nucflag = { path = ".", editable = true }
pyo3-stubgen = "*"

[tool.pixi.tasks]
build = "maturin develop --release"
test = { cmd = "pytest tests/ -v", depends-on = ["build"] }
build_stubs = "pyo3-stubgen py_nucflag"
